### PR TITLE
Conserve better Pokeballs for strong CP Pokemon

### PR DESCRIPTION
**Pull request by cvax**
Instead of wasting good Pokeballs on weak Pokemon, only use them when appropriate.
If no regular Pokeballs left, only use better Pokeballs to capture worthwhile Pokemon instead of wasting them all on 10 CP Pidgeys.

### CODE REVIEW

**Comment by mich3lam** [comment]
@cvax isnt the pokemonCP supposed to be WildPokemon?.PokemonData?.Cp?

pokemonCP is not something that is used? am i wrong?

**Comment by mich3lam** [comment]
ah nvm. i see what u did there :]
kk nice

**Comment by Merudo** [comment]
There is a small bug,

[code] else if ((greatBallsCount < 40 && pokemonCP >= 200) || greatBallsCount >= 40) [/code]

should instead be

[code] else if ((greatBallsCount < 40 && greatBallsCount > 0 && pokemonCP >= 200) || greatBallsCount >= 40) [/code]

**Comment by cvax** [comment]
@Merudo thanks for the catch. Fixed.

**Comment by Ehnoah** [comment]
Please add this

**Comment by LPMassive** [comment]
Yes, you can add it. I use this since he posted it. Works great!

**Comment by Hardell** [comment]
Can someone test this before I merge please?

**Comment by mich3lam** [comment]
It works. I am using it locally

**Pull request merged**
